name: Bug report
about: Report an bug.
title: '[Bug]: '
body:
    - type: checkboxes
      attributes:
          label: Pre-report considerations
          description: Please be prepared to let us know the cause of the bug
          options:
              - label: I have read the [Contributing Guidelines](https://github.com/7086cmd/magnifique/blob/main/CONTRIBUTING.md) for this project.
                required: true
              - label: I agree to follow the [Code of Conduct](https://github.com/7086cmd/magnifique/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
                required: true
              - label: I have searched the [issue tracker](https://www.github.com/7086cmd/magnifique/issues) for a bug report that matches the one I want to file, without success.
                required: true
