name: Bug report
description: Report an bug.
title: '[Bug]: '
labels: ':bug:'
body:
  - type: checkboxes
    attributes:
      label: Pre-report considerations
      description: Please be prepared to let us know the cause of the bug
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/7086cmd/magnifique/blob/main/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/7086cmd/magnifique/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://www.github.com/7086cmd/magnifique/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What is the version your school / you use?
      options:
        - 0.0.0
      validations:
        required: true
  - type: dropdown
    id: place
    attributes:
      label: Where the bug you found?
      options:
        - In the browser
        - In the application
        - 'In requesting("Reference Error")'
  - type: textarea
    attributes:
      value: |
        Thanks for reporting the bug. Please write the reference here.
  - type: input
    attributes:
      label: Contact Details
      description: How can we contact you?
      placeholder: ex. email@example.com
