name: Build App

on:
  release:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  Windows-Build:
    runs-on: [windows-latest]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependences
        run: pnpm install
      - name: Edit Version
        run: 'pnpm edit:version'
      - name: Build
        run: pnpm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
